name: GitHub Classroom Workflow

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Debug GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$GITHUB_TOKEN" ]; then
            echo "✅ GITHUB_TOKEN is set and available"
            echo "Token length: ${#GITHUB_TOKEN}"
          else
            echo "❌ GITHUB_TOKEN is not set"
          fi
      - uses: education/autograding@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}